### ISSUE TITLE
pypi Home Page link is broken

### ISSUE THREAD

**Issue by hoxu** [ionrock/cherrypy-sqlalchemy#2]
https://pypi.python.org/pypi/CherryPy-SQLAlchemy

Points to https://github.com/ionrock/cp_sqlalchemy and the repository seems to have been renamed.

**Comment by ionrock** [comment]
@hoxu Ah hah! Thanks for pointing that out. I'll get it fixed.

**Comment by webknjaz** [comment]
(still broken)

**Comment by webknjaz** [comment]
docs link is broken as well
